var idMk = charIDToTypeID( "Mk  " );
    var desc134 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref12 = new ActionReference();
        var idcontentLayer = stringIDToTypeID( "contentLayer" );
        ref12.putClass( idcontentLayer );
    desc134.putReference( idnull, ref12 );
    var idUsng = charIDToTypeID( "Usng" );
        var desc135 = new ActionDescriptor();
        var idNm = charIDToTypeID( "Nm  " );
        desc135.putString( idNm, """4""" );
        var idType = charIDToTypeID( "Type" );
            var desc136 = new ActionDescriptor();
            var idClr = charIDToTypeID( "Clr " );
                var desc137 = new ActionDescriptor();
                var idRd = charIDToTypeID( "Rd  " );
                desc137.putDouble( idRd, 0.000000 );
                var idGrn = charIDToTypeID( "Grn " );
                desc137.putDouble( idGrn, 0.000000 );
                var idBl = charIDToTypeID( "Bl  " );
                desc137.putDouble( idBl, 0.000000 );
            var idRGBC = charIDToTypeID( "RGBC" );
            desc136.putObject( idClr, idRGBC, desc137 );
        var idsolidColorLayer = stringIDToTypeID( "solidColorLayer" );
        desc135.putObject( idType, idsolidColorLayer, desc136 );
    var idcontentLayer = stringIDToTypeID( "contentLayer" );
    desc134.putObject( idUsng, idcontentLayer, desc135 );
executeAction( idMk, desc134, DialogModes.ALL );